CREATE EXTENSION IF NOT EXISTS citext;

-- =========================
-- ROLES
-- =========================
CREATE TABLE roles (
    role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(50) NOT NULL UNIQUE
);

-- =========================
-- USERS
-- =========================
CREATE TABLE users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email CITEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_role
        FOREIGN KEY (role_id)
        REFERENCES roles(role_id)
        ON DELETE RESTRICT
);

-- =========================
-- LAWYERS
-- =========================
CREATE TABLE lawyers (
    lawyer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    img TEXT,
    display_order INTEGER DEFAULT 0
);

-- =========================
-- AREAS
-- =========================
CREATE TABLE areas (
    area_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    CONSTRAINT uq_areas_name UNIQUE (name)
);

-- =========================
-- LAWYER_AREA (N:M)
-- =========================
CREATE TABLE lawyer_area (
    lawyer_id INTEGER NOT NULL,
    area_id INTEGER NOT NULL,
    PRIMARY KEY (lawyer_id, area_id),
    CONSTRAINT fk_lawyer_area_lawyer
        FOREIGN KEY (lawyer_id)
        REFERENCES lawyers(lawyer_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_lawyer_area_area
        FOREIGN KEY (area_id)
        REFERENCES areas(area_id)
        ON DELETE CASCADE
);

-- =========================
-- NEWS
-- =========================
CREATE TABLE news (
    news_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    content TEXT,
    img_desktop TEXT,
    img_mobile TEXT,
    youtube_url TEXT,
    external_url TEXT,
    slug VARCHAR(200) UNIQUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- =========================
-- CAROUSEL HOME
-- =========================
CREATE TABLE carousel_home (
    carousel_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    img_desktop TEXT,
    img_mobile TEXT,
    display_order INTEGER DEFAULT 0,
    news_id INTEGER,
    CONSTRAINT fk_carousel_news
        FOREIGN KEY (news_id)
        REFERENCES news(news_id)
        ON DELETE SET NULL
);

-- =========================
-- GOOGLE REVIEWS
-- =========================
CREATE TABLE google_reviews (
    review_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_review_id TEXT UNIQUE,
    author_name VARCHAR(100),
    content TEXT,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    profile_photo_url TEXT,
    is_visible BOOLEAN DEFAULT TRUE,
    review_date TIMESTAMPTZ
);

-- =========================
-- INDICES (recomendados)
-- =========================

CREATE INDEX idx_users_role_id ON users(role_id);
CREATE INDEX idx_lawyers_display_order ON lawyers(display_order);
CREATE INDEX idx_news_created_at ON news(created_at);
CREATE INDEX idx_carousel_display_order ON carousel_home(display_order);
CREATE INDEX idx_lawyer_area_area_id ON lawyer_area(area_id);
CREATE INDEX idx_carousel_news_id ON carousel_home(news_id);
CREATE INDEX idx_reviews_visible ON google_reviews(is_visible);